services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    env_file:
      - .env

  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  semaphore-mysql:
    name: semaphore_semaphore-mysql

networks:
  default:
    name: semaphore_default
