services:
  traefik:
    image: traefik:v3.7.1
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    command:
      - --global.sendAnonymousUsage=false
      - --api.dashboard=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.http.tls.certResolver=letsencrypt
      - --providers.docker=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=nd.personal@icloud.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --log.level=info
      - --log.format=common
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filepath=/var/log/traefik/access.log
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53 # Oracle DNS does not work for the DNS challenge.
    volumes:
      - /home/docker-secure/docker-state/traefik/letsencrypt:/letsencrypt
      - /home/docker-secure/docker-state/traefik/logs:/var/log/traefik
      - ./config:/etc/traefik/dynamic:ro
      - /home/docker-secure/docker-compose/KanIDM/internal-certs/traefik/northlake-kanidm-internal-ca.crt:/etc/traefik/certs/northlake-kanidm-internal-ca.crt:ro
    networks:
      - uptime-net
      - kanidm-net
      - vaultwarden-net
      - caddy-net
      - arcane-net
      - semaphore-net

networks:
  uptime-net:
    external: true
  kanidm-net:
    external: true
  vaultwarden-net:
    external: true
  caddy-net:
    external: true
  arcane-net:
    external: true
  semaphore-net:
    external: true
    name: semaphore_default
