http:
  routers:
    status:
      rule: Host(`status.cloud.northlake.dev`) && (Path(`/status`) || PathPrefix(`/status/`) || PathPrefix(`/assets/`) || PathPrefix(`/api/status-page/`) || Path(`/api/entry-page`) || PathPrefix(`/upload/`) || Path(`/favicon.ico`) || Path(`/icon.svg`))
      entryPoints:
        - websecure
      service: status
      priority: 100
      tls:
        certResolver: letsencrypt

    status-admin:
      rule: Host(`status.cloud.northlake.dev`)
      entryPoints:
        - websecure
      service: status
      middlewares:
        - private-net
      priority: 10
      tls:
        certResolver: letsencrypt

    vaultwarden:
      rule: Host(`vault.cloud.northlake.dev`)
      entryPoints:
        - websecure
      service: vaultwarden
      tls:
        certResolver: letsencrypt

    kanidm:
      rule: Host(`idm.northlake.dev`)
      entryPoints:
        - websecure
      service: kanidm
      tls:
        certResolver: letsencrypt

    openbao:
      rule: Host(`secrets.cloud.northlake.dev`)
      entryPoints:
        - websecure
      service: openbao
      middlewares:
        - private-net
      tls:
        certResolver: letsencrypt

    semaphore:
      rule: Host(`semaphore.cloud.northlake.dev`)
      entryPoints:
        - websecure
      service: semaphore
      middlewares:
        - private-net
      tls:
        certResolver: letsencrypt

    arcane:
      rule: Host(`arcane.cloud.northlake.dev`)
      entryPoints:
        - websecure
      service: arcane
      middlewares:
        - private-net
      tls:
        certResolver: letsencrypt

  middlewares:
    private-net:
      ipAllowList:
        sourceRange:
          - 10.0.0.0/24
          - 10.10.0.0/24
          - 10.10.10.0/24
          - 10.10.50.0/24
          - 10.10.60.0/24
          - 10.10.70.0/24
          - 100.86.0.0/16
          - 192.168.100.0/24
          - 72.84.95.56/32
          - 127.0.0.1/32

  services:
    status:
      loadBalancer:
        servers:
          - url: http://uptime-kuma-uptime-kuma-1:3001

    vaultwarden:
      loadBalancer:
        servers:
          - url: http://vaultwarden:80

    kanidm:
      loadBalancer:
        servers:
          - url: https://kanidm:8443
        serversTransport: kanidm-internal

    openbao:
      loadBalancer:
        servers:
          - url: http://openbao:8200

    semaphore:
      loadBalancer:
        servers:
          - url: http://semaphore:3000

    arcane:
      loadBalancer:
        servers:
          - url: http://arcane:3552

  serversTransports:
    kanidm-internal:
      serverName: idm.northlake.dev
      rootCAs:
        - /etc/traefik/certs/northlake-kanidm-internal-ca.crt
