services:
  frigate-oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.0
    container_name: frigate-oauth2-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4180:4180"
    networks:
      - default
      - traefik-net

networks:
  traefik-net:
    external: true
    name: nl10-traefik_traefik-net