services:
  parseable:
    image: quay.io/parseablehq/parseable:latest
    container_name: parseable
    restart: unless-stopped

    command:
      - parseable
      - local-store

    env_file:
      - .env

    volumes:
      - ./data:/parseable/data
      - ./staging:/parseable/staging
