services:
  kanidm:
    image: kanidm/server:latest
    container_name: kanidm
    restart: unless-stopped
    ports:
      - "8443:8443"
    user: "1003:1003"
    env_file:
      - .env
    volumes:
      - kanidm_data:/data
      - /home/docker-secure/certs:/certs:ro
      - /home/docker-secure/docker-compose/KanIDM/app_logos:/app_logos:ro
      - /home/docker-secure/docker-compose/KanIDM/override.css:/hpkg/override.css:ro
#    security_opt:
#      - no-new-privileges:true
#    cap_drop:
#       - ALL
    networks:
      - kanidm-net

networks:
  kanidm-net:
    external: true

volumes:
  kanidm_data:
    external: true
