services:
  kanidm:
    image: kanidm/server:1.11.0
    container_name: kanidm
    restart: unless-stopped

    ports:
      - "8444:8444"

    user: "1003:1003"

    env_file:
      - .env

    volumes:
      - kanidm_data:/data
      - /home/docker-secure/docker-compose/KanIDM/server.toml:/server.toml:ro
      - /home/docker-secure/docker-compose/KanIDM/internal-certs/kanidm:/internal-certs:ro
      - /home/docker-secure/certs:/certs:ro
      - /home/docker-secure/docker-compose/KanIDM/app_logos:/app_logos:ro
      - /home/docker-secure/docker-compose/KanIDM/override.css:/hpkg/override.css:ro

    networks:
      - traefik-private
    labels:
      traefik.enable: "true"
      northlake.traefik.scope: private
      traefik.docker.network: traefik-private
      traefik.http.routers.kanidm.rule: Host(`idm.northlake.dev`)
      traefik.http.routers.kanidm.entrypoints: https
      traefik.http.routers.kanidm.middlewares: private-net@file
      traefik.http.routers.kanidm.tls.certresolver: letsencrypt
      traefik.http.services.kanidm.loadbalancer.server.port: "8443"
      traefik.http.services.kanidm.loadbalancer.server.scheme: https
      traefik.http.services.kanidm.loadbalancer.serverstransport: kanidm-internal@file

networks:
  traefik-private:
    name: traefik-private
    external: true

volumes:
  kanidm_data:
    external: true
