services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
#    user: "1003:1003"
#    cap_add:
#     - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - ./data:/data #caddy_data:/data
      - caddy_config:/config
    networks:
      caddy-net:
      uptime-net:
      kanidm-net:
      vaultwarden-net:
      arcane-net:

volumes:
#  caddy_data:
  caddy_config:

networks:
  caddy-net:
    external: true
  uptime-net:
    external: true
  kanidm-net:
    external: true
  vaultwarden-net:
    external: true
  arcane-net:
    external: true