services:
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:v2.15.0
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        env_file:
            - stack.env
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
